version: '3.7'

services:
    game_data:
        build: .
        volumes:
            - ".:/app"
            - nodemodules:/app/web/node_modules
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
volumes:
    nodemodules:
        driver: "local"